/**
 * @module data-v2/describe-graph
 * The published campus graph in numbers, generated from the Brain's graph export.
 *
 * Hand-written docs explain rules and name the snapshot any example counts come
 * from. Current counts live only in the generated `docs/campus-graph.md`, which
 * `npm run docs:graph -- EXPORT_JSON` rewrites after each release, so they
 * cannot drift from the graph. Download the export from the development Brain's
 * `GET /v1/dev/graph/export` (the Campus Graph page's "Download graph").
 */

interface ExportNode { id: string; kind: string; aliases: string[]; name: string; status?: string; source_bindings?: { collection: string; source_record_keys: string[] }[] }
export interface GraphExport {
  schema: string;
  exported_at: string;
  snapshot: { dataset_version: string; campus_date: string; identity_hash: string; dataset?: { source_commit_sha?: string | null } };
  nodes: ExportNode[];
  edges: { source: string; target: string; type: string }[];
  unresolved_relationships: unknown[];
  contextual_records: { record_type: string }[];
  record_edges: { type: string }[];
  diagnostics: { reason: string; collection?: string | null }[];
  coverage?: { alias_sources?: { sources: { basis: string }[] }[] } | null;
}

const number = (value: number) => value.toLocaleString('en-US');
const fold = (value: string) => value.split(/\s+/).filter(Boolean).join(' ').toLowerCase();

function counts<T>(items: T[], key: (item: T) => string): [string, number][] {
  const result = new Map<string, number>();
  for (const item of items) result.set(key(item), (result.get(key(item)) ?? 0) + 1);
  return [...result].sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]));
}

function table(header: string[], rows: (string | number)[][]): string {
  const line = (cells: (string | number)[]) => `| ${cells.map(cell => typeof cell === 'number' ? number(cell) : cell).join(' | ')} |`;
  return [line(header), line(header.map(() => '---')), ...rows.map(line)].join('\n');
}

/** A coverage reason without the URLs, names and codes that make each one unique. */
export function reasonPattern(reason: string): string {
  return reason
    // A published URL runs to the next space; a sentence's closing period is not part of it.
    .replace(/https?:\/\/\S+?(?=\.?(?:\s|$))/g, '<url>')
    .replace(/"[^"]*"/g, '"…"')
    .replace(/\b[A-Z]{2,5} \d{3}\b/g, '<course>')
    .replace(/\b\d+\b/g, 'N');
}

export function describeGraph(graph: GraphExport): string {
  if (graph.schema !== 'rockygpt.published-campus-knowledge-graph') throw new Error('Expected a published campus knowledge graph export.');
  const linked = new Set(graph.edges.flatMap(edge => [edge.source, edge.target]));
  const kinds = counts(graph.nodes, node => node.kind);
  const byKind = (kind: string) => graph.nodes.filter(node => node.kind === kind);
  const entityRows = kinds.map(([kind, total]) => {
    const nodes = byKind(kind);
    return [kind, total, nodes.filter(node => linked.has(node.id)).length, nodes.reduce((sum, node) => sum + node.aliases.length, 0), nodes.filter(node => node.status === 'retired').length];
  });
  const connected = graph.nodes.filter(node => linked.has(node.id)).length;
  const identities = graph.nodes.filter(node => node.kind !== 'course');
  const connectedIdentities = identities.filter(node => linked.has(node.id)).length;
  const share = (part: number, whole: number) => `${Math.round((part / Math.max(whole, 1)) * 100)}%`;
  const bindings = graph.nodes.flatMap(node => (node.source_bindings ?? []).map(binding => ({ node: node.id, ...binding })));
  const collections = [...new Set(bindings.map(binding => binding.collection))].sort();
  const names = new Map<string, Set<string>>();
  for (const node of graph.nodes) for (const name of [node.name, ...node.aliases]) {
    const ids = names.get(fold(name)) ?? new Set<string>(); ids.add(node.id); names.set(fold(name), ids);
  }
  const aliasTerms = new Set(graph.nodes.flatMap(node => node.aliases.map(fold)));
  const shared = [...aliasTerms].filter(term => (names.get(term)?.size ?? 0) > 1).length;
  const aliasCount = graph.nodes.reduce((sum, node) => sum + node.aliases.length, 0);
  const aliasSources = graph.coverage?.alias_sources;
  const dataCommit = graph.snapshot.dataset?.source_commit_sha;
  return [
    '# Campus graph in numbers',
    '',
    '<!-- Generated by `npm run docs:graph -- EXPORT_JSON` from the Brain\'s graph export. Do not edit by hand. -->',
    '',
    `Generated from the graph export of \`${graph.snapshot.dataset_version}\`. Other docs explain the rules and name the snapshot their examples come from; the current numbers are here. Regenerate this file after each release: download the export from the development Brain (\`GET /v1/dev/graph/export\`, or "Download graph" on the Campus Graph page) and run \`npm run docs:graph -- EXPORT_JSON\`.`,
    '',
    table(['Release', 'Value'], [
      ['Dataset version', `\`${graph.snapshot.dataset_version}\``],
      ['Identity hash', `\`${graph.snapshot.identity_hash}\``],
      ...(dataCommit ? [['Data commit', `\`${dataCommit}\``]] : []),
      ['Campus date', graph.snapshot.campus_date],
      ['Exported', graph.exported_at],
    ]),
    '',
    '## Entities',
    '',
    `${number(graph.nodes.length)} entities; ${number(connected)} (${share(connected, graph.nodes.length)}) have at least one published relationship. Catalog courses are most of the graph and are linked only through faculty profiles; of the other ${number(identities.length)} entities, ${number(connectedIdentities)} (${share(connectedIdentities, identities.length)}) have one.`,
    '',
    table(['Kind', 'Entities', 'With a relationship', 'Aliases', 'Retired'], [...entityRows, ['**Total**', graph.nodes.length, connected, aliasCount, graph.nodes.filter(node => node.status === 'retired').length]]),
    '',
    '## Relationships',
    '',
    `${number(graph.edges.length)} relationships; ${number(graph.unresolved_relationships.length)} published relationships do not resolve to an entity.`,
    '',
    table(['Type', 'Relationships'], counts(graph.edges, edge => edge.type).map(([type, total]) => [`\`${type}\``, total])),
    '',
    '## Linked source records',
    '',
    'The original records each entity\'s identity links name, by collection.',
    '',
    table(['Collection', 'Records', 'Entities'], collections.map(collection => {
      const inCollection = bindings.filter(binding => binding.collection === collection);
      return [collection, inCollection.reduce((sum, binding) => sum + binding.source_record_keys.length, 0), new Set(inCollection.map(binding => binding.node)).size];
    })),
    '',
    '## Aliases',
    '',
    `${number(aliasCount)} aliases under ${number(aliasTerms.size)} names; ${number(shared)} of those names find more than one entity, so a lookup by them asks which one is meant. (A catalog course's code is its alias.)`,
    '',
    aliasSources ? table(['Why the alias exists', 'Aliases'], counts(aliasSources.flatMap(alias => [...new Set(alias.sources.map(source => source.basis))]), basis => basis).map(([basis, total]) => [`\`${basis}\``, total]))
      : 'This release does not record why each alias exists.',
    '',
    '## Requirement groups',
    '',
    table(['Records and edges', 'Count'], [
      ...counts(graph.contextual_records, record => record.record_type).map(([type, total]) => [`\`${type}\` records`, total]),
      ...counts(graph.record_edges, edge => edge.type).map(([type, total]) => [`\`${type}\` edges`, total]),
    ]),
    '',
    '## Coverage issues',
    '',
    `${number(graph.diagnostics.length)} records or links the compiler could not resolve, reported rather than guessed. The most common patterns:`,
    '',
    table(['Collection', 'Issue', 'Count'], counts(graph.diagnostics, issue => `${issue.collection ?? '—'}\u0000${reasonPattern(issue.reason)}`).slice(0, 15).map(([key, total]) => [...key.split('\u0000'), total])),
    '',
  ].join('\n');
}
